haiku/urls.py
from django.urls import path
from . import views


app_name = 'haiku'

urlpatterns = [
    path('', views.index, name='index'),
    # path('', views.IndexView.as_view(), name="index"),
    path('inquiry/',  views.index, name="inquiry"),
    path('detail/<int:pk>/', views.DetailView.as_view(), name="detail"),
]

saiten/urls.py
# from django.urls import path
# from . import views
#
#
# app_name = 'saiten'
# urlpatterns = [
#     path('', views.IndexView.as_view(), name="index"),
#     path('inquiry/', views.InquiryView.as_view(), name="inquiry"),
#     # path('inquiry.html/', views.InquiryView.as_view(), name="inquiry"),
# ]

syukatu_presen/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path, include

from . import settings_common, settings_dev

urlpatterns = [
    path('simeji/', admin.site.urls),
    path('', include('haiku.urls')),
    # path('accounts/', include('allauth.urls')),
    # path('simeji/', include('allauth.urls')),
]

# 開発サーバーでメディアを配信できるようにする設定
urlpatterns += static(settings_common.MEDIA_URL, document_root=settings_dev.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    """拡張ユーザーモデル"""

    class Meta:
        verbose_name_plural = 'CustomUser'

haiku/models.py
from django.db import models
# from accounts.models import CustomUser
# Create your models here.

class Kobo_info(models.Model):

    """公募情報モデル"""

    # user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.PROTECT)

    title = models.CharField(verbose_name='タイトル', max_length=40)
    deadline = models.DateField(verbose_name='締切日', blank=True, null=True)
    prize = models.TextField(verbose_name='賞金', blank=True, null=True)
    contents = models.TextField(verbose_name='募集内容', blank=True, null=True)
    requirements = models.TextField(verbose_name='応募資格', blank=True, null=True)
    sponsor = models.TextField(verbose_name='主催', blank=True, null=True)
    link = models.TextField(verbose_name='応募リンク', blank=True, null=True)

    class Meta:
        verbose_name_plural = 'Kobo_info'

    def __str__(self):
        return self.title



class Saiten_info(models.Model):

    """採点機能に使う過去の入賞作品の分析結果モデル"""

    pos = models.CharField(verbose_name='品詞文字列', max_length=80)
    winningCount = models.PositiveIntegerField(verbose_name='入賞頻度', blank=True, null=True)

    class Meta:
        verbose_name_plural = 'Saiten_info'

    def __str__(self):
        return self.pos

saiten/models.py
from django.db import models

# Create your models here.

class Winning_senryu(models.Model):

    """入賞作品モデル"""

    winning_senryu = models.TextField(verbose_name='入賞作品', blank=True, null=True)

    class Meta:
        verbose_name_plural = 'Winning_senryu'

    def __str__(self):
        return self.winning_senryu

haiku/forms.py
from django import forms
# from django.core.mail import EmailMessage


class SaitenForm(forms.Form):
    haiku = forms.CharField(max_length=30)
    # email = forms.EmailField(label='メールアドレス')
    # title = forms.CharField(label='タイトル', max_length=30)
    # message = forms.CharField(label='メッセージ', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['haiku'].widget.attrs['class'] = 'form-control form-control-lg'
        self.fields['haiku'].widget.attrs['placeholder'] = '川柳・俳句をここに入力'


        # self.fields['email'].widget.attrs['class'] = 'form-control col-11'
        # self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスをここに入力してください。'
        #
        # self.fields['title'].widget.attrs['class'] = 'form-control col-11'
        # self.fields['title'].widget.attrs['placeholder'] = 'タイトルをここに入力してください。'
        #
        # self.fields['message'].widget.attrs['class'] = 'form-control col-12'
        # self.fields['message'].widget.attrs['placeholder'] = 'メッセージをここに入力してください。'

    # def send_email(self):
    #     name = self.cleaned_data['name']
    #     email = self.cleaned_data['email']
    #     title = self.cleaned_data['title']
    #     message = self.cleaned_data['message']
    #
    #     subject = 'お問い合わせ {}'.format(title)
    #     message = '送信者名: {0}\nメールアドレス: {1}\nメッセージ:\n{2}'.format(name, email, message)
    #     from_email = 'admin@example.com'
    #     to_list = [
    #         'test@example.com'
    #     ]
    #     cc_list = [
    #         email
    #     ]
    #
    #     message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, cc=cc_list)
    #     message.send()

accounts/views.py
from django.shortcuts import render

# Create your views here.

haiku/views.py
import logging
import environ
import requests
from django.views import generic
# from .forms import InquiryForm
from django.urls import reverse_lazy
from django.contrib import messages
from .forms import SaitenForm
from django.shortcuts import render

from .models import Kobo_info
from .models import Saiten_info

from bs4 import BeautifulSoup

from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin

# from django.shortcuts import render

# Create your views here.

# .envファイルを読み込み
env = environ.Env()
env.read_env('.env')
# .envファイルからSECRET_KEYを読み込み
API_KEY = env('API_KEY')

logger = logging.getLogger(__name__)

def index(request):
    kobo_list = Kobo_info.objects.order_by('deadline')
    # sessionに保存された俳句をクリア
    request.session.clear()
    return render(request, 'index.html', {'kobo_list': kobo_list})


class IndexView(generic.TemplateView):
    template_name = "index.html"




# class InquiryView(generic.FormView):
#     template_name = "inquiry.html"
#     form_class = InquiryForm
#     success_url = reverse_lazy('haiku:inquiry')
SENTENCE = ""
url = "https://jlp.yahooapis.jp/MAService/V1/parse"
# params = {
#     "appid": API_KEY,
#     "sentence": SENTENCE,
#     # "sentence": "風に火をつける女の片えくぼ",
#     "response": "pos",
# }

class DetailView(generic.DetailView, generic.FormView):
# class DetailView(generic.FormView):
#     model = Saiten_info
    model = Kobo_info
    template_name = "detail.html"

    form_class = SaitenForm


    def post(self, request, *args, **kwargs):
        # self.request.session['haiku'] = self.request.POST.get('haiku')

        SENTENCE = self.request.POST.get('haiku')
        SENTENCE = SENTENCE.strip()
        SENTENCE = SENTENCE.replace(' ', '')
        SENTENCE = SENTENCE.replace('　', '')
        params = {
            "appid": API_KEY,
            "sentence": SENTENCE,
            "response": "pos",
        }
        res = requests.get(url, params=params)
        soup = BeautifulSoup(res.text, 'html.parser')
        word = soup.find_all('pos')
        pos_text = ""
        for text in range(len(word)):
            pos_text += word[text].text



        # 入力された俳句が採点モデルに存在するか？
        if Saiten_info.objects.filter(pos=pos_text).exists():
            pos = Saiten_info.objects.get(pos=pos_text)
            if 20 < pos.winningCount:
                self.request.session['comment'] = "素晴らしい作品ですね！！！"
            elif 15 < pos.winningCount and pos.winningCount < 20:
                self.request.session['comment'] = "とても良い作品ですね！"
            elif 10 < pos.winningCount and pos.winningCount < 15:
                self.request.session['comment'] = "すてきな作品ですね！"
            elif 3 < pos.winningCount and pos.winningCount < 10:
                self.request.session['comment'] = "まあまあの作品ですね"
            elif 0 < pos.winningCount and pos.winningCount < 3:
                self.request.session['comment'] = "まずまずの作品ですね"
            else:
                self.request.session['comment'] = "とても個性的な作品ですね"
        else:
            self.request.session['comment'] = "個性的な作品ですね"

        self.request.session['haiku'] = self.request.POST.get('haiku')
        # self.request.session['haiku'] = pos_text
        return self.get(request, *args, **kwargs)

    # 俳句採点formでsubmitボタンを押した時にリダイレクトさせるようにする
    def get_success_url(self):
        self.request.session['haiku'] = self.POST.get('haiku')
        return reverse('haiku:detail', kwargs={'pk': self.kwargs['pk']})



# class KoboListView(generic.ListView):
#     model = Kobo_info
#
#     template_name = 'index.html'
#
#     def get_queryset(self):
#         order = ('deadline')
#         kobos = Kobo_info.objects.order_by(*order)
#         # kobos = Kobo_info.objects.all()
#
#         cxt = {
#             'kobo_list': kobos
#         }
#
#         return cxt


# def KoboListView(request):
#
#     kobo_list = Kobo_info.objects.all()
#     contest = {
#         'kobo_list': kobo_list,
#     }
#     return render(request, 'index.html', contest)

def list(request):
    data = Kobo_info.objects.all()
    params = {
        'data': data
    }
    return render(request, 'index.html', params)

saiten/views.py
from django.shortcuts import render

# Create your views here.

haiku/templates/base.html
{% load static %}

<html lang="ja">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

        <title>{% block title %}{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
        {% block head %}{% endblock %}
    </head>

    <body>
        <div class="d-flex align-items-end flex-column mb-3">
            <!-- ナビゲーションバー -->
            <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top container-fluid border-bottom">
                <div class="container">
                    <a class="navbar-brand" href="{% url 'haiku:index' %}"><img src="https://user-images.githubusercontent.com/70145199/155842941-f4e3653b-d9ec-4da5-ad1d-a81e5d6071bc.svg"></a>
                 </div>
            </nav>
        </div>

            {% block contents%}{% endblock %}
            {% block kobo_detail %}{% endblock %}


        <!-- フッターエリア -->
        <footer class="footer mt-auto container-fluid" style="padding: 100px 0px 50px 0px">
            <div class="container-fluid bg-white">
                <ul class="nav justify-content-center border-top" style="padding-top: 50px;">
                    <li class="nav-item">
                        <img src="https://user-images.githubusercontent.com/70145199/155842941-f4e3653b-d9ec-4da5-ad1d-a81e5d6071bc.svg">
                    </li>
                </ul>

                <div class="d-flex flex-row bd-highlight mb-3 justify-content-center" style="padding-top: 50px;">
                    <div class="container px-4">
                        <div class="row gx-5">
                            <div class="col">
                                <a href="https://developer.yahoo.co.jp/sitemap/" class="d-flex justify-content-center">
                                    <img src="https://s.yimg.jp/images/yjdn/yjdn_attbtn1_88_35.gif" width="88" height="35" title="Webサービス by Yahoo! JAPAN" alt="Web Services by Yahoo! JAPAN" border="0">
                                </a>
                            </div>
                            <div class="col">
                                <a class="mb-2 link-dark text-decoration-none d-flex justify-content-center" href="/" aria-label="Bootstrap">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="d-block me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg>
                                    <span class="fs-5">Bootstrap</span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <ul class="nav justify-content-center" style="padding-top: 50px;">
                    <li class="nav-item">
                        <p class="fw-light text-black-50" style="font-size: 0.75rem">© 2022 川柳公募支援サイト 〜 詠み人知らず 〜</p>
                    </li>
                </ul>
            </div>
        </footer>
    </body>
</html>

haiku/templates/detail.html
{% extends 'base.html' %}
{% load static %}

{% block kobo_detail %}

    <div class="container d-grid gap-3" style="margin-top: 200px">

        <!-- パンクズリスト -->
        <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'haiku:index' %}" class="fw-light text-success">Top</a></li>
                <li class="breadcrumb-item active" aria-current="page">公募詳細</li>
            </ol>
        </nav>

        <h1>{{ object.title }}</h1>
        <h2>採点してみる</h2>
        <div class="container p-2 border border-1 rounded-3" style="--bs-bg-opacity: .5;">

            <form method="post" action="">

                {% csrf_token %}

                <div class="mb-3">
                    <label for="exampleInputEmail1" class="form-label">川柳・俳句を入力</label>
{#                    <input type="text" class="form-control form-control-lg" id="exampleInputEmail1" aria-describedby="emailHelp" name="haiku">#}
                        {{ form.non_field_errors }}

                        {% for field in form %}
{#                            <div class="form-group row">#}
{#                                <label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label">#}
{#                                    <strong>{{ field.label_tag }}</strong>#}
{#                                </label>#}
{#                                <div class="col-sm-8">#}

                                    {{ field }}
                                    {{ field.errors }}
{#                                </div>#}
{#                            </div>#}
                        {% endfor %}
                    <div id="emailHelp" class="form-text">入力例：閑さや 岩にしみ入る 蝉の声</div>
                </div>

                <button type="submit" class="btn btn-outline-success">採点する</button>

                {# formを入力したら表示 #}
                {% if request.session.haiku %}
                    <div class="alert alert-success" role="alert" style="margin-top: 2rem">
                        <h4 class="alert-heading">
                            {{ request.session.comment }}
                        </h4>
    {#                    <p>Aww yeah, you successfully read this important alert message. This example text is going to run a bit longer so that you can see how spacing within an alert works with this kind of content.</p>#}
                        <hr>
                        <p class="fs-1">{{ request.session.haiku }}</p>
    {#                    <p class="mb-0">Whenever you need to, be sure to use margin utilities to keep things nice and tidy.</p>#}
                    </div>
                {% endif %}
{#                <div class="card">#}
{#                    <div class="card-header">#}
{#                    Quote#}
{#                    </div>#}
{#                    <div class="card-body">#}
{#                    <blockquote class="blockquote mb-0">#}
{#                      <p>A well-known quote, contained in a blockquote element.</p>#}
{#                      <footer class="blockquote-footer">Someone famous in <cite title="Source Title">Source Title</cite></footer>#}
{#                    </blockquote>#}
{#                    </div>#}
{#                </div>#}
            </form>
        </div>

        <dl class="d-grid gap-3">
            <dt>懸賞</dt>
            <dd>{{ object.prize }}</dd>
            <dt>応募先</dt>
            <dd><a href="{{ object.link }}" class="fw-light text-success" target="_blank" rel="noopener noreferrer">{{ object.link }}</a></dd>
            <dt>締切</dt>
            <dd>{{ object.deadline }}</dd>
            <dt>公募テーマ</dt>
            <dd>{{ object.contents }}</dd>
            <dt>参加資格</dt>
            <dd>{{ object.requirements }}</dd>
            <dt>主催</dt>
            <dd>{{ object.sponsor }}</dd>
        </dl>
    </div>

{% endblock %}

haiku/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block contents %}

    <div class="container" style="margin-top: 200px">

        <!-- パンクズリスト -->
        <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <!-- <li class="breadcrumb-item"><a href="#">Home</a></li> -->
                <li class="breadcrumb-item active" aria-current="page">Top</li>
            </ol>
        </nav>

        <!-- メインコンテンツエリア -->

            <!-- 新着情報とおすすめ記事 -->
            <div class="row gy-4">
                <div class="col-12 col-sm-6">
                    <div class="card overflow-hidden" style="height: 22rem">
                        <div class="card-body">
                            <h5 class="card-title">新着情報</h5>
                            {% for kobo in kobo_list %}
                                {% if forloop.counter < 6 %}
                                    <div class="d-flex flex-row bd-highlight">
                                        <div class="bd-highlight">
                                            <a href="{% url 'haiku:detail' kobo.pk %}" class="card-text fw-light text-success text-decoration-none"><p>
                                                {{ kobo.title }}
                                            </p></a>
                                        </div>
                                        <div class="p-1 bd-highlight">
                                            {% if kobo.title %}
                                                <span class="badge rounded-pill bg-warning bg-gradient">New</span><br>
                                            {% endif %}
                                        </div>
                                    </div>
                                {% else %}
                                {% endif %}
                            {% empty %}
                                <p>公募がありません。。。。</p>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="col-12 col-sm-6">
                    <div class="card" style="height: 22rem">
                        <div class="card-body">
                            <h5 class="card-title">おすすめ</h5>
                            <p class="card-text">
                                題：{{ kobo_list.0.title }}
                            </p>
                            <p class="card-text text-truncate">
                                賞金：{{ kobo_list.0.prize }}
                            </p>
                            <p class="card-text">
                                締切：{{ kobo_list.0.deadline }}
                            </p>
                            <p class="card-text text-truncate">応募リンク：<a href="{{ kobo_list.0.link }}" class="card-link fw-light text-success">
                                {{ kobo_list.0.link }}
                            </a></p>
                            <a href="{% url 'haiku:detail' kobo_list.0.pk %}" class="btn btn-success">もっと詳しく</a>
                        </div>
                    </div>
                </div>

                <!-- 公募情報エリア -->
                <div class="col-12" style="margin-top: 5rem">
                    <h2 class="border-bottom">公募情報の一覧</h2>
                </div>
                {% for kobo in kobo_list %}
                <div class="col-12">
                    <div class="card p-3">
                        <div class="card-body">
                            <h5 class="card-title">
                                {{ kobo.title }}
                            </h5>
                            <p class="card-text text-truncate">
                                賞金：{{ kobo.prize }}
                            </p>
                            <p class="card-text">
                                締切：{{ kobo.deadline }}
                            </p>
                            <p class="card-text text-truncate">
                                募集内容：{{ kobo.contents }}
                            </p>
                            <p class="card-text text-truncate">応募リンク：<a href="{{ kobo.link }}" class="card-link fw-light text-success">
                                {{ kobo.link }}
                            </a></p>
                            <a href="{% url 'haiku:detail' kobo.pk %}" class="btn btn-success">もっと詳しく</a>
                        </div>
                    </div>
                </div>
                {% empty %}
                <p>公募がありません。。。。</p>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

haiku/templates/inquiry.html
{% extends 'base.html' %}

{% block title %}お問い合わせ | 俳句（仮）{% endblock %}

{% block active_inquiry %}active{% endblock %}

{% block contents %}
<div class="container" style="margin-top: 100px">
    <p>Hey</p>
{#    <div class="row">#}
{#        <div class="my-div-style">#}
{#            <form method="post">#}
{#                {% csrf_token %}#}
{##}
{#                {{ form.non_field_errors }}#}
{##}
{#                {% for field in form %}#}
{#                    <div class="form-group row">#}
{#                        <label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label">#}
{#                            <strong>{{ field.label_tag }}</strong>#}
{#                        </label>#}
{#                        <div class="col-sm-8">#}
{#                            {{ field }}#}
{#                            {{ field.errors }}#}
{#                        </div>#}
{#                    </div>#}
{#                {% endfor %}#}
{##}
{#                <div class="offset-sm-4 col-sm-8">#}
{#                    <button class="btn btn-primary" type="submit">送信</button>#}
{#                </div>#}
{#            </form>#}
{#        </div>#}
{#    </div>#}
</div>
{% endblock %}

haiku/templates/kobo_list.html
{#{% extends 'index.html' %}#}
{#{% load static %}#}

{#{% block kobo_info%}#}

    {% for kobo in data %}
{#    {% for kobo in kobo_info %}#}
        <div class="card" style="height: 300px;">
            <div class="card-body">
                <h5 class="card-title">
                    {{ kobo.title }}
                </h5>
                <p>あれれ？</p>
                <p class="card-text">
                    {{ kobo.deadline }}
                </p>
                <p class="card-text">
                    {{ kobo.prize }}
                </p>
                <p class="card-text">
                    {{ kobo.contents }}
                </p>
                <p class="card-text">
                    {{ kobo.requirements }}
                </p>
                <p class="card-text">応募リンク：<a href="https://present.eonet.jp/senryupre21120301/" class="card-link">
                    {{ kobo.link }}
                </a></p>
                <a href="{% url 'haiku:detail' %}" class="btn btn-primary">もっと詳しく</a>
            </div>
        </div>
    {% empty %}
        <p>公募がありません。</p>
    {% endfor %}
{##}
{##}
{##}
{##}
{##}
{#            <div class="card" style="height: 300px;">#}
{#                <div class="card-body">#}
{#                    <h5 class="card-title">女性活躍川柳</h5>#}
{#                    <p class="card-text">賞金：VISAギフトカード　10,000円分</p>#}
{#                    <p class="card-text">締切：2022年01月01日</p>#}
{#                    <p class="card-text">募集内容：「論理的」をお題にした川柳</p>#}
{#                    <p class="card-text">応募リンク：<a href="https://www.sdgswip.com/pages/5514498/static" class="card-link">https://www.sdgswip.com/pages/5514498/static</a></p>#}
{#                    <a href="#" class="btn btn-primary">もっと詳しく</a>#}
{#                </div>#}
{#            </div>#}
{#            <div class="card" style="height: 300px;">#}
{#                <div class="card-body">#}
{#                    <h5 class="card-title">まるせん　論理的川柳コンテスト</h5>#}
{#                    <p class="card-text">賞金：ギフト券 500円分</p>#}
{#                    <p class="card-text">締切：2021年12月31日</p>#}
{#                    <p class="card-text">募集内容：「薬」をお題とした川柳を募集</p>#}
{#                    <p class="card-text">応募リンク：<a href="https://marusenryu.com/contest/269" class="card-link">https://marusenryu.com/contest/269</a></p>#}
{#                    <a href="#" class="btn btn-primary">もっと詳しく</a>#}
{#                </div>#}
{#            </div>#}
{##}
{#{% endblock %}#}

saiten/templates/apply_form.html
{% extends 'base.html' %}

{% block title %}Log In | Private Diary{% endblock %}

{% block active_login %}active{% endblock %}

{% block contents %}

<!-- メインコンテンツエリア -->
<div class="d-grid gap-4">

    <!-- 公募情報エリア -->
    <div class="card" style="height: 300px;">
        <div class="card-body">
            <h5 class="card-title">Card title</h5>
            <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        </div>
    </div>
</div>

{% endblock %}